apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
      kubernetes.io/ingress.class: nginx
  name: go-ingress
spec:
  rules:
    - host: webn.danielk8s.tk
      http:
        paths:
          - backend:
              serviceName: golb-service
              servicePort: 8090
            path: /
